quarkus:
  http:
    port: ${HTTP_PORT:8084}
  
  datasource:
    db-kind: postgresql
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppassword}
    jdbc:
      url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/appdb}
  
  hibernate-orm:
    database:
      generation: update
  
  log:
    category:
      "org.hibernate.SQL":
        level: INFO
  
  smallrye-openapi:
    path: /q/openapi
  
  swagger-ui:
    always-include: true
    path: /q/swagger-ui

# JWT Configuration
mp:
  jwt:
    verify:
      algorithm: HS256
      publickey: ${JWT_SECRET:super-secret-change-me-please-change-me-32-bytes}
      issuer: ${JWT_ISSUER:users-service}

# Kafka Configuration - Listen to multiple topics
mp.messaging:
  incoming:
    order-events-in:
      connector: smallrye-kafka
      topic: order.events
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group.id: notifications-service-group
      auto.offset.reset: earliest
      fetch.max.bytes: 10485760
    
    article-events-in:
      connector: smallrye-kafka
      topic: article.events
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group.id: notifications-service-group
      auto.offset.reset: earliest
      fetch.max.bytes: 10485760

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
