quarkus:
  arc:
    selected-alternatives:
      - org.acme.notifications.config.JwtAuthContextProducer
  http:
    port: ${HTTP_PORT:8084}
  
  datasource:
    db-kind: postgresql
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppassword}
    jdbc:
      url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/appdb}
  
  hibernate-orm:
    database:
      generation: update
  
  log:
    category:
      "org.hibernate.SQL":
        level: INFO
  
  smallrye-openapi:
    path: ${OPENAPI_PATH:/openapi/notifications}

  swagger-ui:
    always-include: true
    path: ${SWAGGER_PATH:/swagger/notifications}

# JWT Configuration
jwt:
  issuer: ${JWT_ISSUER:users-service}
  algorithm: ${JWT_ALGORITHM:HS256}
  secret: ${JWT_SECRET:super-secret-change-me-please-change-me-32-bytes-minimum-length}

# Kafka Configuration - Listen to multiple topics
mp.messaging:
  incoming:
    order-events:
      connector: smallrye-kafka
      topic: order-events
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group.id: notifications-service-orders-group
      auto.offset.reset: earliest
      fetch.max.bytes: 10485760
      enable.auto.commit: false
      commit-strategy: throttled
      failure-strategy: ignore
      max.poll.records: 500
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    article-events:
      connector: smallrye-kafka
      topic: article-events
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group.id: notifications-service-articles-group
      auto.offset.reset: earliest
      fetch.max.bytes: 10485760
      enable.auto.commit: false
      commit-strategy: throttled
      failure-strategy: ignore
      max.poll.records: 500
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
